app:
  progress bar: true

parser:
  paths:
    - "."
    - "."
  combine files: true
  autodetect: true
  sample size: -1
  header: true
  separator: ","
  date format: "auto"
  timestamp format: "auto"

performance:
  memory limit: 4
  threads count: 2

database:
  table names:
    - "my_table"

post import:
  validate data: false
  create indexes: true
  indexes:
    - "ID"